spring.application.name=TelegramBot
telegram.bot-token=${BOT_TOKEN}
telegram.bot-username=${BOT_USERNAME}

# PostgreSQL Database Configurations (Supabase vb)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=4
